# Generated by Django 4.2.5 on 2023-09-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("image", models.ImageField(default="writer.png", upload_to="writer")),
                ("twitter", models.CharField(default="#", max_length=255)),
                ("facebook", models.CharField(default="#", max_length=255)),
                ("instagram", models.CharField(default="#", max_length=255)),
                ("status", models.BooleanField(default=False)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "writerimage",
                    models.ImageField(default="default.jpg", upload_to="writerimage"),
                ),
                (
                    "contentimage",
                    models.ImageField(default="default.jpg", upload_to="contentimage"),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("quote", models.TextField()),
                ("price", models.IntegerField(default=0)),
                ("counted_comment", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("category", models.ManyToManyField(to="blogs.category")),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blogs.writer"
                    ),
                ),
            ],
            options={"ordering": ("-created_date",),},
        ),
    ]
