# Generated by Django 4.2.5 on 2023-10-03 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio")),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=100)),
                (
                    "project_date",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 10, 3, 7, 39, 46, 493770)
                    ),
                ),
                ("content", models.TextField()),
                ("title", models.TextField()),
                ("projecturl", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("category", models.ManyToManyField(to="portfolio.category")),
                ("image", models.ManyToManyField(to="portfolio.portfolioimage")),
            ],
            options={"ordering": ("-created_date",),},
        ),
    ]
