# Generated by Django 4.2.5 on 2023-09-28 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 28, 6, 36, 49, 338277)
            ),
        ),
    ]
